version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: petrovi4s/backend:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c 'python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py import_csv &&
      gunicorn --build 0:8000 foodgram.wsgi'
    restart: always

  frontend:
    image: petrovi4s/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value: